### ISSUE TITLE
Both should control UI (and use x)

### ISSUE THREAD

**Issue by dairykillsme** [The-First-Pancake/cappy_and_tappy#3]
Both controllers don't currently control the UI. In addition `x` should be allowed to select UI inputs.

**Comment by dairykillsme** [comment]
@DeclanMorrison you mean for UI menus only right? That's a good idea. I'll implement that.

**Comment by oliveman521** [comment]
If we allow X for UI navigation, we should also make it drop blocks

**Comment by dairykillsme** [comment]
I don't agree that is necessary. X is an expectation for UI navigation in video games in general, but there isn't an expectation that game controls match UI controls.
