### ISSUE TITLE
CoOp Splash Screen

### ISSUE THREAD

**Issue by dairykillsme** [The-First-Pancake/cappy_and_tappy#5]

**Comment by DeclanMorrison** [comment]
Context on this? Not sure what it means.

**Comment by dairykillsme** [comment]
Oliver's idea, but as I understand it, this would be a splash screen a boot that says something like: Play solo (over an image of a keyboard and mouse and a single person) or with a friend (over a keyboard and mouse split between two people). Also factor the controllers in there, not sure what exactly Oliver has planned. Mostly to show what types of inputs are allowed
